### ISSUE TITLE
View Booking Page

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Restaurant-Booking-Project#1]
EPIC: Make a Booking

As a **User** I can **visit the site** so that **I can make a booking**

**Acceptance Criteria**
- [ ] A user doesn't have to log in to book
- [ ] A user can see if a slot is available or not
- [ ] Users are directed to the booking page when visiting the site

**Tasks**
- [ ] Set up booking page
- [ ] Add calendar so users can view dates they'd like to book
- [ ] Users can choose a day from the calendar
- [ ] Set up a database to store bookings
- [ ] Link database to calendar
