### ISSUE TITLE
Account Registration

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Restaurant-Booking-Project#2]
EPIC: User Profile

As a **User** I can **create an account** so that **I can view my bookings**

**Acceptance Criteria**
- [ ] A user can create an account with their email
- [ ] A user can log in once the account has been created
- [ ] A user can see their past and upcoming bookings when logged in
- [ ] A user can edit their upcoming bookings once logged in

**Tasks**
- [ ] Set up a login page
- [ ] Add a link in the homepage to the login page
- [ ] Implement registration functionality
- [ ] Test login feature
- [ ] Link User's profile to their booking requests
