### ISSUE TITLE
View Booking Requests

### ISSUE THREAD

**Issue by JoeOrtiz1995** [JoeOrtiz1995/Restaurant-Booking-Project#3]
EPIC: Superuser Profile

As a **Superuser** I can **create an account** so that **I can view booking requests**

**Acceptance Criteria**
- A superuser can create an account with their email
- A superuser can log into their account
- A superuser can view booking requests from the admin panel

**Tasks**
- [ ] Set up admin page so that only a superuser can access it
- [ ] All booking requests are accessible from the admin panel
- [ ] Link database with booking requests to admin panel
